version: "3.7"

services:
  dwg-ping:
    build: .
    container_name: dwg-ping
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - SOURCE_ID=${SOURCE_ID}
      - TEST_INTERVAL_MIN=5
